// GENERATED by tool/gen_story_tests.dart — DO NOT EDIT.
// Regenerate: flutter test tool/gen_story_tests.dart
//
// One light golden, one dark golden and one expectUiSane per story in
// the `card-proposal` component. Goldens SKIP off Linux
// (eden-ui-flutter#32); expectUiSane runs on every platform.
//
// Each expectUiSane call names the input modality its story DECLARES
// (EdenStory.inputModality): pointer asserts WCAG 2.5.8 24x24, touch
// asserts the 48dp/44pt floors. It selects the standard; it waives
// nothing.

import 'package:flutter_test/flutter_test.dart';

import '../../../test_support/ui_oracle/story_harness.dart';

void main() {
  setUp(ensureStoriesRegistered);

  testWidgets('card-proposal/applied — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/applied'),
        themeMode: ThemeMode.light,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/applied — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/applied'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('card-proposal/applied — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/applied'),
        themeMode: ThemeMode.dark,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/applied — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/applied'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('card-proposal/narrow — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/narrow'),
        themeMode: ThemeMode.light,
        width: 390,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/narrow — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/narrow'),
        themeMode: ThemeMode.light,
        width: 390);
  }, skip: kGoldenSkip);

  testWidgets('card-proposal/narrow — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/narrow'),
        themeMode: ThemeMode.dark,
        width: 390,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/narrow — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/narrow'),
        themeMode: ThemeMode.dark,
        width: 390);
  }, skip: kGoldenSkip);

  testWidgets('card-proposal/pending — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/pending'),
        themeMode: ThemeMode.light,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/pending — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/pending'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('card-proposal/pending — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/pending'),
        themeMode: ThemeMode.dark,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/pending — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/pending'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('card-proposal/read-only — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/read-only'),
        themeMode: ThemeMode.light,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/read-only — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/read-only'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('card-proposal/read-only — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('card-proposal/read-only'),
        themeMode: ThemeMode.dark,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('card-proposal/read-only — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('card-proposal/read-only'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);
}
