// GENERATED by tool/gen_story_tests.dart — DO NOT EDIT.
// Regenerate: flutter test tool/gen_story_tests.dart
//
// One light golden, one dark golden and one expectUiSane per story in
// the `desktop-layout` component. Goldens SKIP off Linux
// (eden-ui-flutter#32); expectUiSane runs on every platform.

import 'package:flutter_test/flutter_test.dart';

import '../../../test_support/ui_oracle/story_harness.dart';

void main() {
  setUp(ensureStoriesRegistered);

  testWidgets('desktop-layout/default — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('desktop-layout/default'),
        themeMode: ThemeMode.light);
  });

  testWidgets('desktop-layout/default — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('desktop-layout/default'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('desktop-layout/default — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('desktop-layout/default'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('desktop-layout/default — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('desktop-layout/default'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('desktop-layout/narrow — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('desktop-layout/narrow'),
        themeMode: ThemeMode.light);
  });

  testWidgets('desktop-layout/narrow — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('desktop-layout/narrow'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('desktop-layout/narrow — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('desktop-layout/narrow'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('desktop-layout/narrow — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('desktop-layout/narrow'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);
}
