// GENERATED by tool/gen_story_tests.dart — DO NOT EDIT.
// Regenerate: flutter test tool/gen_story_tests.dart
//
// One light golden, one dark golden and one expectUiSane per story in
// the `error-refusal` component. Goldens SKIP off Linux
// (eden-ui-flutter#32); expectUiSane runs on every platform.
//
// Each expectUiSane call names the input modality its story DECLARES
// (EdenStory.inputModality): pointer asserts WCAG 2.5.8 24x24, touch
// asserts the 48dp/44pt floors. It selects the standard; it waives
// nothing.

import 'package:flutter_test/flutter_test.dart';

import '../../../test_support/ui_oracle/story_harness.dart';

void main() {
  setUp(ensureStoriesRegistered);

  testWidgets('error-refusal/refusal — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('error-refusal/refusal'),
        themeMode: ThemeMode.light,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('error-refusal/refusal — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('error-refusal/refusal'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('error-refusal/refusal — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('error-refusal/refusal'),
        themeMode: ThemeMode.dark,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('error-refusal/refusal — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('error-refusal/refusal'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('error-refusal/tool-named — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('error-refusal/tool-named'),
        themeMode: ThemeMode.light,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('error-refusal/tool-named — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('error-refusal/tool-named'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('error-refusal/tool-named — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('error-refusal/tool-named'),
        themeMode: ThemeMode.dark,
        inputModality: EdenInputModality.touch);
  });

  testWidgets('error-refusal/tool-named — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('error-refusal/tool-named'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);
}
