// GENERATED by tool/gen_story_tests.dart — DO NOT EDIT.
// Regenerate: flutter test tool/gen_story_tests.dart
//
// One light golden, one dark golden and one expectUiSane per story in
// the `nav-item` component. Goldens SKIP off Linux
// (eden-ui-flutter#32); expectUiSane runs on every platform.

import 'package:flutter_test/flutter_test.dart';

import '../../../test_support/ui_oracle/story_harness.dart';

void main() {
  setUp(ensureStoriesRegistered);

  testWidgets('nav-item/badge — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/badge'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/badge — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/badge'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/badge — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/badge'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/badge — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/badge'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/caption — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/caption'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/caption — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/caption'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/caption — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/caption'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/caption — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/caption'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/default — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/default'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/default — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/default'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/default — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/default'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/default — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/default'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/divider — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/divider'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/divider — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/divider'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/divider — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/divider'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/divider — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/divider'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/expandable-collapsed — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/expandable-collapsed'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/expandable-collapsed — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/expandable-collapsed'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/expandable-collapsed — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/expandable-collapsed'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/expandable-collapsed — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/expandable-collapsed'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/expandable-expanded — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/expandable-expanded'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/expandable-expanded — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/expandable-expanded'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/expandable-expanded — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/expandable-expanded'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/expandable-expanded — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/expandable-expanded'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/long-label — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/long-label'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/long-label — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/long-label'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/long-label — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/long-label'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/long-label — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/long-label'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/selected — light — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/selected'),
        themeMode: ThemeMode.light);
  });

  testWidgets('nav-item/selected — light — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/selected'),
        themeMode: ThemeMode.light);
  }, skip: kGoldenSkip);

  testWidgets('nav-item/selected — dark — expectUiSane', (tester) async {
    await expectStorySane(tester, storyById('nav-item/selected'),
        themeMode: ThemeMode.dark);
  });

  testWidgets('nav-item/selected — dark — golden$kGoldenSkipSuffix',
      (tester) async {
    await expectStoryGolden(tester, storyById('nav-item/selected'),
        themeMode: ThemeMode.dark);
  }, skip: kGoldenSkip);
}
