// Behaviour tests for tool/gen_stories.dart (TRD 23-03, cases 1-4).
//
// The generator is split into a PURE core (generateRegistrationSource,
// storyFileFromRelativePath) and a thin IO shell (discoverStoryFiles, main).
// These tests drive the pure core over HAND-BUILT inputs -- no fixture is
// generated, and at the time this TRD landed there were zero real
// `<widget>.stories.dart` files in the tree (23-05 adds the first).

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../../tool/gen_stories.dart';

// --------------------------------------------------------------------------
// Hand-built inputs. Deliberately given in NON-sorted order so case 1 proves
// the generator sorts rather than echoing input order.
// --------------------------------------------------------------------------

const StoryFile _navItem = StoryFile(
  importPath: '../../src/widgets/eden_layout/eden_nav_item.stories.dart',
  symbol: 'edenNavItemStories',
);

const StoryFile _appShell = StoryFile(
  importPath: '../../src/widgets/eden_layout/eden_app_shell.stories.dart',
  symbol: 'edenAppShellStories',
);

void main() {
  group('generateRegistrationSource', () {
    test('case 1: emits sorted imports and one register loop per story file',
        () {
      final source = generateRegistrationSource(const [_navItem, _appShell]);

      // Fixed header, naming the regeneration command.
      expect(source, startsWith('// GENERATED by tool/gen_stories.dart'));
      expect(source, contains('flutter test tool/gen_stories.dart'));

      // Sorted by import path: eden_app_shell before eden_nav_item, even
      // though the input listed nav_item first.
      final appShellImport =
          source.indexOf("import '${_appShell.importPath}';");
      final navItemImport = source.indexOf("import '${_navItem.importPath}';");
      expect(appShellImport, isNonNegative);
      expect(navItemImport, isNonNegative);
      expect(appShellImport, lessThan(navItemImport));

      // One registration loop each, in the same sorted order.
      expect(
        source,
        contains(
            'for (final s in ${_appShell.symbol}) {\n    registry.register(s);\n  }'),
      );
      expect(
        source,
        contains(
            'for (final s in ${_navItem.symbol}) {\n    registry.register(s);\n  }'),
      );
      expect(
        source.indexOf(_appShell.symbol),
        lessThan(source.lastIndexOf(_navItem.symbol)),
      );

      expect(source, contains('void registerGeneratedStories() {'));
      expect(source, endsWith('\n'));
    });

    test('case 2: generating twice over the same input is byte-identical', () {
      final a = generateRegistrationSource(const [_navItem, _appShell]);
      final b = generateRegistrationSource(const [_appShell, _navItem]);
      expect(b, equals(a));
    });

    test('case 3: zero story files yields a valid, story-free source', () {
      final source = generateRegistrationSource(const []);

      expect(source, contains('void registerGeneratedStories() {'));
      expect(source, contains('no co-located'));
      // No unused import and no unused local -- both would be analyzer
      // findings on a file that is committed to the tree.
      expect(source, isNot(contains("import 'story_registry.dart';")));
      expect(source, isNot(contains('final registry =')));
      expect(source, endsWith('\n'));
    });
  });

  group('storyFileFromRelativePath', () {
    test('derives the <name>Stories symbol and a registry-relative import', () {
      final f = storyFileFromRelativePath('src/widgets/eden_layout/eden_nav_item.stories.dart');
      expect(f.symbol, 'edenNavItemStories');
      expect(f.importPath, '../../src/widgets/eden_layout/eden_nav_item.stories.dart');
    });
  });

  group('discoverStoryFiles', () {
    late Directory tmp;

    setUp(() {
      tmp = Directory.systemTemp.createTempSync('gen_stories_test');
    });

    tearDown(() {
      if (tmp.existsSync()) tmp.deleteSync(recursive: true);
    });

    test('case 4: a .stories.dart missing its List<EdenStory> export throws, naming the file',
        () {
      File('${tmp.path}/widgets/eden_thing.stories.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('// no story list here\n');

      expect(
        () => discoverStoryFiles(tmp),
        throwsA(
          isA<StoryFileContractError>().having(
            (e) => e.toString(),
            'message',
            allOf(
              contains('widgets/eden_thing.stories.dart'),
              contains('edenThingStories'),
            ),
          ),
        ),
      );
    });

    test('discovers a conforming story file and sorts by path', () {
      File('${tmp.path}/widgets/b_thing.stories.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('final List<EdenStory> bThingStories = [];\n');
      File('${tmp.path}/widgets/a_thing.stories.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync('final List<EdenStory> aThingStories = [];\n');

      final found = discoverStoryFiles(tmp);
      expect(found.map((f) => f.symbol).toList(),
          ['aThingStories', 'bThingStories']);
    });
  });
}
