// Behaviour tests for tool/gen_story_tests.dart (TRD 23-03, cases 6-7).
//
// Pure core over a HAND-BUILT two-story registry — no fixture is generated.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:eden_ui_flutter/dev_app/registry/eden_story.dart';

import '../../tool/gen_story_tests.dart';

EdenStory _story(String component, String name) => EdenStory(
      id: '$component/$name',
      component: component,
      name: name,
      knobs: const [],
      build: (context, _) => const SizedBox.shrink(),
    );

void main() {
  final buttons = [_story('buttons', 'interactive'), _story('buttons', 'all')];

  group('generateStoryTestSource', () {
    test('case 6: one testWidgets per (story, theme), naming the raw story id',
        () {
      final source = generateStoryTestSource('buttons', buttons);

      expect(source, startsWith('// GENERATED by tool/gen_story_tests.dart'));
      expect(source, contains(kRegenerateStoryTestsCommand));

      // Raw ids (with the '/') survive into the test NAMES so a failure
      // message names the story.
      for (final id in ['buttons/all', 'buttons/interactive']) {
        for (final theme in ['light', 'dark']) {
          expect(source, contains("testWidgets('$id — $theme — expectUiSane'"));
          expect(source,
              contains("testWidgets('\$id — \$theme — golden\\\$kGoldenSkipSuffix'"));
        }
      }

      // The golden expectations carry the platform skip; expectUiSane must NOT.
      // `testWidgets` takes `bool? skip`, not a reason String (23-05 finding):
      // the bool gates the skip, the suffix keeps the reason in the test name.
      expect(source, contains('}, skip: kGoldenSkip);'));
      final saneIndex = source.indexOf("— light — expectUiSane'");
      final saneBodyEnd = source.indexOf('});', saneIndex);
      expect(saneIndex, isNonNegative);
      expect(saneBodyEnd, isNonNegative);

      // Harness reached by RELATIVE import (23-01's convention).
      expect(source,
          contains("import '../../../test_support/ui_oracle/story_harness.dart';"));
      expect(source, endsWith('\n'));
    });

    test('case 7: emitted output is byte-stable and input-order independent',
        () {
      final a = generateStoryTestSource('buttons', buttons);
      final b = generateStoryTestSource('buttons', buttons.reversed.toList());
      expect(b, equals(a));
      expect(generateStoryTestSource('buttons', buttons), equals(a));
    });
  });

  group('storyTestFileName', () {
    test('sanitises a hyphenated component into a dart file name', () {
      expect(storyTestFileName('badges-alerts'), 'badges_alerts_stories_test.dart');
    });
  });

  group('generateStoryTestSources', () {
    test('groups stories by component, one file per component', () {
      final sources = generateStoryTestSources([
        ...buttons,
        _story('cards', 'all'),
      ]);
      expect(sources.keys.toList(), ['buttons_stories_test.dart', 'cards_stories_test.dart']);
    });
  });
}
