// GENERATED by tool/gen_stories.dart — DO NOT EDIT.
// Regenerate: flutter test tool/gen_stories.dart
//
// Registration for co-located `<widget>.stories.dart` files. This is the
// FIFTH story group; the four hand-written groups in register_all.dart are
// untouched by this generator.
// Drift between this file and a fresh generation fails test/stories/registry_drift_test.dart.

void registerGeneratedStories() {
  // no co-located `<widget>.stories.dart` files discovered under lib/ yet.
}
