// GENERATED by tool/gen_stories.dart — DO NOT EDIT.
// Regenerate: flutter test tool/gen_stories.dart
//
// Registration for co-located `<widget>.stories.dart` files. This is the
// FIFTH story group; the four hand-written groups in register_all.dart are
// untouched by this generator.
// Drift between this file and a fresh generation fails test/stories/registry_drift_test.dart.

import 'story_registry.dart';
import '../../src/widgets/eden_layout/eden_desktop_layout.stories.dart';
import '../../src/widgets/eden_layout/eden_mobile_layout.stories.dart';
import '../../src/widgets/eden_layout/eden_nav_item.stories.dart';

void registerGeneratedStories() {
  final registry = StoryRegistry.instance;
  for (final s in edenDesktopLayoutStories) {
    registry.register(s);
  }
  for (final s in edenMobileLayoutStories) {
    registry.register(s);
  }
  for (final s in edenNavItemStories) {
    registry.register(s);
  }
}
