// tool/gen_story_tests.dart
//
// Emits one `flutter test` file per story component under
// `test/stories/_generated/`, asserting for every story a LIGHT golden, a DARK
// golden and `expectUiSane`. A story that is not tested is a demo.
//
// HOW TO RUN — via the flutter test runner, NOT plain `dart`:
//
//   flutter test tool/gen_story_tests.dart
//
// (The registry transitively imports package:flutter/material.dart, so a bare
// `dart run` fails to resolve dart:ui.)
//
// INPUT SET — stated plainly, because it is the one judgement call here:
// the generator covers the stories contributed by CO-LOCATED
// `<widget>.stories.dart` files (the ones tool/gen_stories.dart registers),
// not the 49 hand-written dev-app stories that predate this objective. Those 49
// are already pumped by test/dev_app/registry/registry_complete_test.dart;
// generating ~196 golden/oracle tests over screens built before the oracle
// existed would turn the suite red on day one, and closing that gap is 23-04's
// ratchet to schedule rather than this TRD's to force.
// At the time this landed the co-located set is EMPTY (23-05 adds the first),
// so `test/stories/_generated/` holds only its .gitkeep.
//
// DETERMINISM: components sorted, stories sorted by name — the same key
// StoryRegistry.all() uses — fixed header, trailing newline.

import 'dart:io';

import 'package:eden_ui_flutter/dev_app/registry/eden_story.dart';
import 'package:eden_ui_flutter/dev_app/registry/register_stories.g.dart';
import 'package:eden_ui_flutter/dev_app/registry/story_registry.dart';
import 'package:flutter_test/flutter_test.dart';

/// Directory (relative to the package root) the generated tests are written to.
const String kGeneratedTestDir = 'test/stories/_generated';

/// The command that regenerates [kGeneratedTestDir].
const String kRegenerateStoryTestsCommand =
    'flutter test tool/gen_story_tests.dart';

/// `badges-alerts` -> `badges_alerts_stories_test.dart`.
String storyTestFileName(String component) =>
    '${component.replaceAll('-', '_')}_stories_test.dart';

/// PURE. Emits the generated test file source for one [component].
String generateStoryTestSource(String component, List<EdenStory> stories) {
  final sorted = [...stories]..sort((a, b) => a.name.compareTo(b.name));

  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_story_tests.dart — DO NOT EDIT.')
    ..writeln('// Regenerate: $kRegenerateStoryTestsCommand')
    ..writeln('//')
    ..writeln('// One light golden, one dark golden and one expectUiSane per story in')
    ..writeln('// the `$component` component. Goldens SKIP off Linux')
    ..writeln('// (eden-ui-flutter#32); expectUiSane runs on every platform.')
    ..writeln('//')
    ..writeln('// Each expectUiSane call names the input modality its story DECLARES')
    ..writeln('// (EdenStory.inputModality): pointer asserts WCAG 2.5.8 24x24, touch')
    ..writeln('// asserts the 48dp/44pt floors. It selects the standard; it waives')
    ..writeln('// nothing.')
    ..writeln()
    ..writeln("import 'package:flutter_test/flutter_test.dart';")
    ..writeln()
    ..writeln("import '../../../test_support/ui_oracle/story_harness.dart';")
    ..writeln()
    ..writeln('void main() {')
    ..writeln('  setUp(ensureStoriesRegistered);');

  for (final s in sorted) {
    // Emitted VERBATIM from the story when it declares one, never defaulted
    // here. The VIEWPORT a surface is measured at must be readable at the
    // assertion, exactly like the tap-target floor below it: a story whose
    // width is inherited from a harness default is a story nobody can tell
    // was measured at the wrong width — which is how two goldens came to be
    // byte-identical to their siblings.
    final viewport = s.viewportWidth == null
        ? ''
        : '\n        width: ${_literal(s.viewportWidth!)},';
    // The golden call takes no `inputModality`, so the width is its LAST
    // argument; a story that declares none must emit byte-identically to
    // before, or every baseline in the catalogue churns for nothing.
    final goldenTail = s.viewportWidth == null
        ? ');'
        : ',\n        width: ${_literal(s.viewportWidth!)});';
    for (final theme in const ['light', 'dark']) {
      b
        ..writeln()
        ..writeln("  testWidgets('${s.id} — $theme — expectUiSane', (tester) async {")
        ..writeln("    await expectStorySane(tester, storyById('${s.id}'),")
        ..writeln('        themeMode: ThemeMode.$theme,$viewport')
        // Emitted VERBATIM from the story, never defaulted here. The tap-target
        // floor a surface is held to must be readable at the assertion.
        ..writeln(
            '        inputModality: EdenInputModality.${s.inputModality.name});')
        ..writeln('  });')
        ..writeln()
        ..writeln(
            "  testWidgets('${s.id} — $theme — golden\$kGoldenSkipSuffix',")
        ..writeln('      (tester) async {')
        ..writeln("    await expectStoryGolden(tester, storyById('${s.id}'),")
        ..writeln('        themeMode: ThemeMode.$theme$goldenTail')
        ..writeln('  }, skip: kGoldenSkip);');
    }
  }

  b.writeln('}');
  return b.toString();
}

/// A `double` written the way a reader would write it: `720`, not `720.0`,
/// when it is whole.
String _literal(double value) =>
    value == value.roundToDouble() ? '${value.round()}' : '$value';

/// PURE. Groups [stories] by component and emits one source per component,
/// keyed by file name, in sorted key order.
Map<String, String> generateStoryTestSources(List<EdenStory> stories) {
  final byComponent = <String, List<EdenStory>>{};
  for (final s in stories) {
    byComponent.putIfAbsent(s.component, () => []).add(s);
  }
  final components = byComponent.keys.toList()..sort();
  return {
    for (final c in components)
      storyTestFileName(c): generateStoryTestSource(c, byComponent[c]!),
  };
}

/// The stories contributed by co-located `<widget>.stories.dart` files — the
/// set this generator covers. Read off the COMMITTED generated registration,
/// so it is empty until 23-05 lands the first co-located story.
List<EdenStory> coLocatedStories() {
  // [3J[H[2J is @visibleForTesting; this file is test-only support reached by
  // relative import from test/, but it lives outside test/ so the analyzer
  // cannot see that. Scoped ignore with the reason rather than widening the
  // registry's API.
  // ignore: invalid_use_of_visible_for_testing_member
  StoryRegistry.instance.clear();
  registerGeneratedStories();
  return StoryRegistry.instance.all();
}

void main() {
  test('generate the story tests', () {
    final stories = coLocatedStories();
    final sources = generateStoryTestSources(stories);
    final dir = Directory(kGeneratedTestDir)..createSync(recursive: true);
    for (final existing in dir.listSync()) {
      if (existing is File && existing.path.endsWith('_stories_test.dart')) {
        existing.deleteSync();
      }
    }
    sources.forEach((name, source) {
      File('${dir.path}/$name').writeAsStringSync(source);
    });
    stdout.writeln('gen_story_tests: wrote ${sources.length} file(s) for '
        '${stories.length} co-located story/stories -> $kGeneratedTestDir');
    expect(sources.length, stories.isEmpty ? 0 : greaterThan(0));
  });
}
